apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        env:
        - name: DB_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        ports:
        - containerPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.backend.serviceType }}
  ports:
  - port: 5000
    targetPort: {{ .Values.backend.port }}
  selector:
    app: backend
