name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: write # 🔓 This unlocks the ability to push manifest updates

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Needed to push changes back to the repo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 🚀 Build and Push with UNIQUE TAG (GitHub SHA)
      - name: Build and Push Backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/ecommerce-backend:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/ecommerce-backend:$IMAGE_TAG

      - name: Build and Push Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          VITE_API_URL: http://a9d97f0211a274da08442f6d39336e4c-1162729234.ap-south-1.elb.amazonaws.com/api
        run: |
          docker build -t $ECR_REGISTRY/ecommerce-frontend:$IMAGE_TAG \
            --build-arg VITE_API_URL=$VITE_API_URL ./frontend
          docker push $ECR_REGISTRY/ecommerce-frontend:$IMAGE_TAG

      # 🪄 GITOPS MAGIC: Update the YAML files with the new Image Tag
      - name: Update Kubernetes Manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|image:.*ecommerce-backend:.*|image: $ECR_REGISTRY/ecommerce-backend:$IMAGE_TAG|g" k8s/backend-deployment.yaml
          sed -i "s|image:.*ecommerce-frontend:.*|image: $ECR_REGISTRY/ecommerce-frontend:$IMAGE_TAG|g" k8s/frontend-deployment.yaml
          
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/
          git commit -m "Auto-update images to $IMAGE_TAG [skip ci]"
          git push origin main
